### ISSUE TITLE
runtime error: racy use of timers

### ISSUE THREAD

**Issue by mrd0ll4r** [libp2p/go-yamux#20]
Got this while running IPFS, but I figured it probably belongs here:

```
panic: runtime error: racy use of timers

goroutine 247502 [running]:
time.resetTimer(0xc003d3ff48, 0x3fc2d5cfdd34)
        /usr/local/go/src/runtime/time.go:233 +0x35
time.(*Timer).Reset(0xc003d3ff40, 0x6fc23ac00, 0x0)
        /usr/local/go/src/time/sleep.go:126 +0x7d
github.com/libp2p/go-yamux.(*Session).startKeepalive.func1()
        /home/leo/go/pkg/mod/github.com/libp2p/go-yamux@v1.3.1/session.go:345 +0x19e
created by time.goFunc
        /usr/local/go/src/time/sleep.go:168 +0x44
```

This is on go-ipfs commit 67741060c4332d27b6434559db3e6270444b1125, the daemon says this on startup:
```
go-ipfs version: 0.5.0-dev-67741060c
Repo version: 7
System version: amd64/linux
Golang version: go1.14
```

It's actually WSL, I built without CGO.

Here's another:
```
panic: runtime error: racy use of timers

goroutine 109005 [running]:
time.resetTimer(0xc002d589b8, 0x422c5ec82298)
        /usr/local/go/src/runtime/time.go:233 +0x35
time.(*Timer).Reset(0xc002d589b0, 0x6fc23ac00, 0xc002bd6300)
        /usr/local/go/src/time/sleep.go:126 +0x7d
github.com/libp2p/go-yamux.(*Session).recvLoop(0xc00393ef70, 0x0, 0x0)
        /home/leo/go/pkg/mod/github.com/libp2p/go-yamux@v1.3.1/session.go:516 +0x302
github.com/libp2p/go-yamux.(*Session).recv(0xc00393ef70)
        /home/leo/go/pkg/mod/github.com/libp2p/go-yamux@v1.3.1/session.go:483 +0x2b
created by github.com/libp2p/go-yamux.newSession
        /home/leo/go/pkg/mod/github.com/libp2p/go-yamux@v1.3.1/session.go:129 +0x379
```

**Comment by Stebalien** [comment]
Thank you for noticing this, you've saved me a _lot_ of hassle trying to track this down later.
